### ISSUE TITLE
Too many spawned scripts

### ISSUE THREAD

**Issue by Sparker95** [Apricot-ale/Apricots-MW-NVG-VFX#1]
Hi, so about the issue we discussed:

It looks like that this spawns the script for every soldier created in the game:
https://github.com/Apricot-ale/Apricots-MW-NVG-VFX/blob/dfd15dd33f66a87e0c8bb1f813e7d0f8399a778e/IBISS_Vfx_NVG/IBISS_Vfx_NVG/config.cpp#L47-L58

We need to figure out how to make it spawn only one script on player's machine. I think you can do it through CfgFunctions preInit or postInit flag. Perhaps you can ask at arma discord what's the best way to manage life cycle of the postprocessing effect, there are many people who can help with that, I just didn't have to solve it myself yet.

**Comment by Apricot-ale** [comment]
I see the problem.
I'm hoping to find a way to fix it somehow.
Thank you.

**Comment by Apricot-ale** [comment]
It's may fixed at main branch rewrite.
