### ISSUE TITLE
Extreme .RPT Spam on Headless Clients

### ISSUE THREAD

**Issue by Quailsnap** [Apricot-ale/Apricots-MW-NVG-VFX#12]
Loading MW-NVG-VFX on a Headless Client can result in massive RPT spam. This has been the case since early December, at least, and can produce log files >1.0GB. If I have more time to test tomorrow, I will reproduce it and get you the error, but I recall it being related to when the script attempts to add the EH to the client.

**Comment by Apricot-ale** [comment]
Duplicate of #1 .
Maybe....

This will fix new version.
